packwiz mr add https://modrinth.com/mod/artifacts
packwiz mr add https://modrinth.com/mod/xaeros-minimap
packwiz mr add https://modrinth.com/mod/moonlight
packwiz mr add https://modrinth.com/mod/lets-do-brewery-farmcharm-compat
packwiz mr add https://modrinth.com/mod/xaeros-world-map
packwiz mr add https://modrinth.com/mod/beautify-refabricated
packwiz mr add https://modrinth.com/mod/immersive-paintings
packwiz mr add https://modrinth.com/mod/create-man-of-many-planes
packwiz mr add https://modrinth.com/mod/indium
packwiz mr add https://modrinth.com/mod/lithostitched
packwiz mr add https://modrinth.com/mod/armourers-workshop
packwiz mr add https://modrinth.com/mod/puzzles-lib
packwiz mr add https://modrinth.com/mod/dramatic-doors
packwiz mr add https://modrinth.com/mod/kubejs
packwiz mr add https://modrinth.com/mod/every-compat
packwiz mr add https://modrinth.com/mod/vmp-fabric
packwiz mr add https://modrinth.com/mod/no-resource-pack-warnings
packwiz mr add https://modrinth.com/mod/botany-pots
packwiz mr add https://modrinth.com/mod/resourcify
packwiz mr add https://modrinth.com/mod/botany-trees
packwiz mr add https://modrinth.com/mod/create-fabric
packwiz mr add https://modrinth.com/mod/immersive-aircraft
packwiz mr add https://modrinth.com/mod/create-dreams-and-desires
packwiz mr add https://modrinth.com/mod/lmd
packwiz mr add https://modrinth.com/mod/terrablender
packwiz mr add https://modrinth.com/mod/modernfix
packwiz mr add https://modrinth.com/mod/chat-heads
packwiz mr add https://modrinth.com/mod/athena-ctm
packwiz mr add https://modrinth.com/mod/fabric-api
packwiz mr add https://modrinth.com/mod/friends-and-foes
packwiz mr add https://modrinth.com/mod/no-chat-reports
packwiz mr add https://modrinth.com/mod/comforts
packwiz mr add https://modrinth.com/mod/log-cleaner
packwiz mr add https://modrinth.com/mod/voice-chat-interaction
packwiz mr add https://modrinth.com/resourcepack/redstone-torch-backport
packwiz mr add https://modrinth.com/mod/lithium
packwiz mr add https://modrinth.com/mod/handcrafted
packwiz mr add https://modrinth.com/mod/createaddition
packwiz mr add https://modrinth.com/mod/lets-do-meadow
packwiz mr add https://modrinth.com/mod/deltaboxlib
packwiz mr add https://modrinth.com/mod/servercore
packwiz mr add https://modrinth.com/mod/jade
packwiz mr add https://modrinth.com/mod/twigs
packwiz mr add https://modrinth.com/mod/lexiconfig
packwiz mr add https://modrinth.com/mod/xaero-zoomout
packwiz mr add https://modrinth.com/mod/itemphysic-lite
packwiz mr add https://modrinth.com/mod/particle-rain
packwiz mr add https://modrinth.com/mod/macaws-trapdoors
packwiz mr add https://modrinth.com/mod/copycats
packwiz mr add https://modrinth.com/mod/entitytexturefeatures
packwiz mr add https://modrinth.com/mod/jade-addons-fabric
packwiz mr add https://modrinth.com/mod/freecam
packwiz mr add https://modrinth.com/mod/create-pattern-schematics
packwiz mr add https://modrinth.com/mod/rechiseled
packwiz mr add https://modrinth.com/mod/supermartijn642s-config-lib
packwiz mr add https://modrinth.com/mod/zoomify
packwiz mr add https://modrinth.com/mod/playeranimator
packwiz mr add https://modrinth.com/mod/tooltipfix
packwiz mr add https://modrinth.com/mod/audioplayer
packwiz mr add https://modrinth.com/mod/interiors
packwiz mr add https://modrinth.com/mod/el-and-ls-dye-mod
packwiz mr add https://modrinth.com/mod/1.21.2-bundle-recipe
packwiz mr add https://modrinth.com/mod/eating-animation
packwiz mr add https://modrinth.com/mod/supplementaries
packwiz mr add https://modrinth.com/mod/polymorph
packwiz mr add https://modrinth.com/mod/serene-seasons
packwiz mr add https://modrinth.com/mod/glitchcore
packwiz mr add https://modrinth.com/mod/farmers-delight-refabricated
packwiz mr add https://modrinth.com/mod/almanac
packwiz mr add https://modrinth.com/mod/emi
packwiz mr add https://modrinth.com/mod/iris
packwiz mr add https://modrinth.com/mod/fps-reducer
packwiz mr add https://modrinth.com/mod/resourceful-lib
packwiz mr add https://modrinth.com/mod/elytra-trims
packwiz mr add https://modrinth.com/mod/natures-spirit
packwiz mr add https://modrinth.com/mod/jei
packwiz mr add https://modrinth.com/mod/backport-paintings-1.21
packwiz mr add https://modrinth.com/mod/amendments
packwiz mr add https://modrinth.com/mod/geckolib
packwiz mr add https://modrinth.com/mod/fabric-language-kotlin
packwiz mr add https://modrinth.com/mod/dynamicsurroundingsfabric
packwiz mr add https://modrinth.com/mod/cosmetic-armor
packwiz mr add https://modrinth.com/mod/modmenu
packwiz mr add https://modrinth.com/mod/fast-item-frames
packwiz mr add https://modrinth.com/mod/macaws-stairs
packwiz mr add https://modrinth.com/mod/rechiseled-create
packwiz mr add https://modrinth.com/mod/ksyxis
packwiz mr add https://modrinth.com/mod/blur-plus
packwiz mr add https://modrinth.com/mod/sophisticated-backpacks-(unoffical-fabric-port)
packwiz mr add https://modrinth.com/mod/accessories
packwiz mr add https://modrinth.com/mod/iris-flw-compat
packwiz mr add https://modrinth.com/mod/rhino
packwiz mr add https://modrinth.com/resourcepack/fresh-animations
packwiz mr add https://modrinth.com/mod/debugify
packwiz mr add https://modrinth.com/shader/complementary-reimagined
packwiz mr add https://modrinth.com/mod/sodium-options-api
packwiz mr add https://modrinth.com/mod/mouse-tweaks
packwiz mr add https://modrinth.com/mod/bookshelf-lib
packwiz mr add https://modrinth.com/mod/emojiful
packwiz mr add https://modrinth.com/mod/sodium-extras
packwiz mr add https://modrinth.com/mod/fancymenu
packwiz mr add https://modrinth.com/mod/cccbridge
packwiz mr add https://modrinth.com/mod/simple-radio
packwiz mr add https://modrinth.com/mod/bellsandwhistles
packwiz mr add https://modrinth.com/mod/observable
packwiz mr add https://modrinth.com/mod/reeses-sodium-options
packwiz mr add https://modrinth.com/mod/biomes-o-plenty
packwiz mr add https://modrinth.com/mod/kubejs-additions
packwiz mr add https://modrinth.com/mod/faithful-mace
packwiz mr add https://modrinth.com/mod/fastquit
packwiz mr add https://modrinth.com/mod/cc-tweaked
packwiz mr add https://modrinth.com/mod/wwoo
packwiz mr add https://modrinth.com/mod/lets-do-bakery-farmcharm-compat
packwiz mr add https://modrinth.com/mod/leaves-be-gone
packwiz mr add https://modrinth.com/mod/create-connected-fabric
packwiz mr add https://modrinth.com/mod/carry-on
packwiz mr add https://modrinth.com/mod/forge-config-api-port
packwiz mr add https://modrinth.com/mod/custom-player-models
packwiz mr add https://modrinth.com/mod/simple-voice-chat
packwiz mr add https://modrinth.com/mod/fzzy-config
packwiz mr add https://modrinth.com/mod/macaws-doors
packwiz mr add https://modrinth.com/mod/yacl
packwiz mr add https://modrinth.com/mod/architectury-api
packwiz mr add https://modrinth.com/mod/lets-do-farm-charm
packwiz mr add https://modrinth.com/mod/sitting+
packwiz mr add https://modrinth.com/mod/better-clouds
packwiz mr add https://modrinth.com/mod/not-enough-animations
packwiz mr add https://modrinth.com/mod/jinxedlib
packwiz mr add https://modrinth.com/mod/numismatics
packwiz mr add https://modrinth.com/mod/controlling
packwiz mr add https://modrinth.com/mod/sodium-extra
packwiz mr add https://modrinth.com/mod/create-enchantment-industry-fabric
packwiz mr add https://modrinth.com/mod/fog
packwiz mr add https://modrinth.com/mod/sophisticated-core-(unofficial-fabric-port)
packwiz mr add https://modrinth.com/mod/trinkets
packwiz mr add https://modrinth.com/mod/elytra-slot
packwiz mr add https://modrinth.com/mod/coroutil
packwiz mr add https://modrinth.com/mod/presence-footsteps
packwiz mr add https://modrinth.com/mod/what-are-they-up-to
packwiz mr add https://modrinth.com/mod/storagedrawers
packwiz mr add https://modrinth.com/mod/ferrite-core
packwiz mr add https://modrinth.com/mod/wakes
packwiz mr add https://modrinth.com/mod/chipped
packwiz mr add https://modrinth.com/mod/entity-model-features
packwiz mr add https://modrinth.com/mod/distanthorizons
packwiz mr add https://modrinth.com/mod/create-steam-n-rails
packwiz mr add https://modrinth.com/mod/seasonhud-fabric
packwiz mr add https://modrinth.com/mod/fusion-connected-textures
packwiz mr add https://modrinth.com/mod/enchancement
packwiz mr add https://modrinth.com/mod/searchables
packwiz mr add https://modrinth.com/mod/man-of-many-planes
packwiz mr add https://modrinth.com/mod/artsandcrafts-compatibility
packwiz mr add https://modrinth.com/mod/sodium
packwiz mr add https://modrinth.com/mod/axiom
packwiz mr add https://modrinth.com/mod/artsandcrafts
packwiz mr add https://modrinth.com/mod/sodium-options-mod-compat
packwiz mr add https://modrinth.com/mod/modelfix
packwiz mr add https://modrinth.com/mod/txnilib
packwiz mr add https://modrinth.com/mod/cloth-config
packwiz mr add https://modrinth.com/mod/remote-player-waypoints-for-xaeros-map
packwiz mr add https://modrinth.com/mod/lazydfu
packwiz mr add https://modrinth.com/mod/clumps
packwiz mr add https://modrinth.com/mod/mru
packwiz mr add https://modrinth.com/mod/starlight
packwiz mr add https://modrinth.com/mod/supermartijn642s-core-lib
packwiz mr add https://modrinth.com/mod/trimmable-tools
packwiz mr add https://modrinth.com/mod/lets-do-bloomingnature
packwiz mr add https://modrinth.com/mod/konkrete
packwiz mr add https://modrinth.com/resourcepack/ferns-fancy-inventory
packwiz mr add https://modrinth.com/mod/packet-fixer
packwiz mr add https://modrinth.com/mod/reintegrated-arts-and-crafts
packwiz mr add https://modrinth.com/mod/c2me-fabric
packwiz mr add https://modrinth.com/mod/actually-unbreaking
packwiz mr add https://modrinth.com/mod/pehkui
packwiz mr add https://modrinth.com/mod/e4mc
packwiz mr add https://modrinth.com/mod/lets-do-candlelight-farmcharm-compat
packwiz mr add https://modrinth.com/mod/more-mob-variants
packwiz mr add https://modrinth.com/mod/creativecore
packwiz mr add https://modrinth.com/mod/melody
packwiz mr add https://modrinth.com/mod/accessories-tc-layer
packwiz mr add https://modrinth.com/mod/decorative-blocks
packwiz mr add https://modrinth.com/mod/trowel
packwiz mr add https://modrinth.com/resourcepack/just-expressions
packwiz mr add https://modrinth.com/mod/pottery-sherd-duplication
packwiz mr add https://modrinth.com/mod/talkbubbles
packwiz mr add https://modrinth.com/mod/subtle-effects
packwiz mr add https://modrinth.com/mod/create-deco
packwiz mr add https://modrinth.com/mod/macaws-bridges