name = "Train Yard Season 3"
author = "EternalBlade55"
version = "3.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5134dce3a747e64d55ca4f5f6de7e5eaf6dd576b7c711260ef393ec655102949"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.231"

[options]
datapack-folder = "config/paxi/datapacks"
