name = "Train Yard Season 3"
author = "EternalBlade55"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0baffa0e112d06b54c71947a2d9bd0dd09f504e2c0c01a7dde938b0eb93dc155"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
