name = "Train Yard Season 3"
author = "EternalBlade55"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e1e6312cf422ec8423c4298dc0f4e09a3e36b11028a7b8c643da5b41eeead8c"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
