StartupEvents.registry("block", (event) => {
	//Creation Of Blocks

	event
		.create("stored_uranium_ingots")
		.displayName("Stored Uranium Ingots")
		.mapColor("color_green")
		.stoneSoundType()
		.tagBlock("minecraft:mineable/pickaxe")
		.tagBlock("minecraft:needs_wooden_tool")
		.hardness(2)
		.resistance(4)
		.opaque(true)
		.fullBlock(true)
		.requiresTool(true)
		.renderType("solid")
		.texture(Direction.UP, "kubejs:block/stored_uranium_ingots_top")
		.texture(Direction.DOWN, "kubejs:block/stored_ingots_bottom")
		.texture(Direction.NORTH, "kubejs:block/stored_uranium_ingots_side")
		.texture(Direction.SOUTH, "kubejs:block/stored_uranium_ingots_side")
		.texture(Direction.EAST, "kubejs:block/stored_uranium_ingots_front")
		.texture(Direction.WEST, "kubejs:block/stored_uranium_ingots_front")
		.texture("particle", "kubejs:block/stored_uranium_ingots_top")
		.suffocating(true)
		.viewBlocking(true)
		.redstoneConductor(true)
		.transparent(false);

	event
		.create("stored_silver_ingots")
		.displayName("Stored Silver Ingots")
		.mapColor("color_light_gray")
		.stoneSoundType()
		.tagBlock("minecraft:mineable/pickaxe")
		.tagBlock("minecraft:needs_wooden_tool")
		.hardness(2)
		.resistance(4)
		.opaque(true)
		.fullBlock(true)
		.requiresTool(true)
		.renderType("solid")
		.texture(Direction.UP, "kubejs:block/stored_silver_ingots_top")
		.texture(Direction.DOWN, "kubejs:block/stored_bottom")
		.texture(Direction.NORTH, "kubejs:block/stored_silver_ingots_side")
		.texture(Direction.SOUTH, "kubejs:block/stored_silver_ingots_side")
		.texture(Direction.EAST, "kubejs:block/stored_silver_ingots_front")
		.texture(Direction.WEST, "kubejs:block/stored_silver_ingots_front")
		.texture("particle", "kubejs:block/stored_silver_ingots_top")
		.suffocating(true)
		.viewBlocking(true)
		.redstoneConductor(true)
		.transparent(false);

	event
		.create("stored_nickel_aluminide_ingots")
		.displayName("Stored Nickel Aluminide Ingots")
		.mapColor("color_light_gray")
		.stoneSoundType()
		.tagBlock("minecraft:mineable/pickaxe")
		.tagBlock("minecraft:needs_wooden_tool")
		.hardness(2)
		.resistance(4)
		.opaque(true)
		.fullBlock(true)
		.requiresTool(true)
		.renderType("solid")
		.texture(
			Direction.UP,
			"kubejs:block/stored_nickel_aluminide_ingots_top",
		)
		.texture(Direction.DOWN, "kubejs:block/stored_ingots_bottom")
		.texture(
			Direction.NORTH,
			"kubejs:block/stored_nickel_aluminide_ingots_side",
		)
		.texture(
			Direction.SOUTH,
			"kubejs:block/stored_nickel_aluminide_ingots_side",
		)
		.texture(
			Direction.EAST,
			"kubejs:block/stored_nickel_aluminide_ingots_front",
		)
		.texture(
			Direction.WEST,
			"kubejs:block/stored_nickel_aluminide_ingots_front",
		)
		.texture("particle", "kubejs:block/stored_nickel_aluminide_ingots_top")
		.suffocating(true)
		.viewBlocking(true)
		.redstoneConductor(true)
		.transparent(false);

	event
		.create("stored_canvas")
		.displayName("Stored Canvas")
		.mapColor("color_brown")
		.grassSoundType()
		.hardness(0.5)
		.resistance(1)
		.opaque(true)
		.fullBlock(true)
		.requiresTool(false)
		.renderType("solid")
		.texture(Direction.UP, "farmersdelight:block/canvas_rug")
		.texture(Direction.DOWN, "farmersdelight:block/canvas_rug")
		.texture(Direction.NORTH, "farmersdelight:block/canvas_rug")
		.texture(Direction.SOUTH, "farmersdelight:block/canvas_rug")
		.texture(Direction.EAST, "farmersdelight:block/canvas_rug")
		.texture(Direction.WEST, "farmersdelight:block/canvas_rug")
		.texture("particle", "farmersdelight:block/canvas_rug")
		.suffocating(true)
		.viewBlocking(true)
		.redstoneConductor(true)
		.transparent(false);

	event
		.create("cobbled_crimsite")
		.displayName("Cobbled Crimsite")
		.mapColor("color_red")
		.stoneSoundType()
		.tagBlock("minecraft:mineable/pickaxe")
		.tagBlock("minecraft:needs_wooden_tool")
		.hardness(2)
		.resistance(4)
		.opaque(true)
		.fullBlock(true)
		.requiresTool(true)
		.renderType("solid")
		.texture(Direction.UP, "kubejs:block/cobbled_crimsite")
		.texture(Direction.DOWN, "kubejs:block/cobbled_crimsite")
		.texture(Direction.NORTH, "kubejs:block/cobbled_crimsite")
		.texture(Direction.SOUTH, "kubejs:block/cobbled_crimsite")
		.texture(Direction.EAST, "kubejs:block/cobbled_crimsite")
		.texture(Direction.WEST, "kubejs:block/cobbled_crimsite")
		.texture("particle", "kubejs:block/cobbled_crimsite")
		.suffocating(true)
		.viewBlocking(true)
		.redstoneConductor(true)
		.transparent(false);

	event
		.create("cobbled_asurine")
		.displayName("Cobbled Asurine")
		.mapColor("color_blue")
		.stoneSoundType()
		.tagBlock("minecraft:mineable/pickaxe")
		.tagBlock("minecraft:needs_wooden_tool")
		.hardness(2)
		.resistance(4)
		.opaque(true)
		.fullBlock(true)
		.requiresTool(true)
		.renderType("solid")
		.texture(Direction.UP, "kubejs:block/cobbled_asurine")
		.texture(Direction.DOWN, "kubejs:block/cobbled_asurine")
		.texture(Direction.NORTH, "kubejs:block/cobbled_asurine")
		.texture(Direction.SOUTH, "kubejs:block/cobbled_asurine")
		.texture(Direction.EAST, "kubejs:block/cobbled_asurine")
		.texture(Direction.WEST, "kubejs:block/cobbled_asurine")
		.texture("particle", "kubejs:block/cobbled_asurine")
		.suffocating(true)
		.viewBlocking(true)
		.redstoneConductor(true)
		.transparent(false);

	event
		.create("cobbled_ochrum")
		.displayName("Cobbled Ochrum")
		.mapColor("color_yellow")
		.stoneSoundType()
		.tagBlock("minecraft:mineable/pickaxe")
		.tagBlock("minecraft:needs_wooden_tool")
		.hardness(2)
		.resistance(4)
		.opaque(true)
		.fullBlock(true)
		.requiresTool(true)
		.renderType("solid")
		.texture(Direction.UP, "kubejs:block/cobbled_ochrum")
		.texture(Direction.DOWN, "kubejs:block/cobbled_ochrum")
		.texture(Direction.NORTH, "kubejs:block/cobbled_ochrum")
		.texture(Direction.SOUTH, "kubejs:block/cobbled_ochrum")
		.texture(Direction.EAST, "kubejs:block/cobbled_ochrum")
		.texture(Direction.WEST, "kubejs:block/cobbled_ochrum")
		.texture("particle", "kubejs:block/cobbled_ochrum")
		.suffocating(true)
		.viewBlocking(true)
		.redstoneConductor(true)
		.transparent(false);

	event
		.create("cobbled_veridium")
		.displayName("Cobbled Veridium")
		.mapColor("color_green")
		.stoneSoundType()
		.tagBlock("minecraft:mineable/pickaxe")
		.tagBlock("minecraft:needs_wooden_tool")
		.hardness(2)
		.resistance(4)
		.opaque(true)
		.fullBlock(true)
		.requiresTool(true)
		.renderType("solid")
		.texture(Direction.UP, "kubejs:block/cobbled_veridium")
		.texture(Direction.DOWN, "kubejs:block/cobbled_veridium")
		.texture(Direction.NORTH, "kubejs:block/cobbled_veridium")
		.texture(Direction.SOUTH, "kubejs:block/cobbled_veridium")
		.texture(Direction.EAST, "kubejs:block/cobbled_veridium")
		.texture(Direction.WEST, "kubejs:block/cobbled_veridium")
		.texture("particle", "kubejs:block/cobbled_veridium")
		.suffocating(true)
		.viewBlocking(true)
		.redstoneConductor(true)
		.transparent(false);

	event
		.create("cobbled_gabbro")
		.displayName("Cobbled Gabbro")
		.mapColor("terracotta_white")
		.stoneSoundType()
		.tagBlock("minecraft:mineable/pickaxe")
		.tagBlock("minecraft:needs_wooden_tool")
		.hardness(2)
		.resistance(4)
		.opaque(true)
		.fullBlock(true)
		.requiresTool(true)
		.renderType("solid")
		.texture(Direction.UP, "kubejs:block/cobbled_gabbro")
		.texture(Direction.DOWN, "kubejs:block/cobbled_gabbro")
		.texture(Direction.NORTH, "kubejs:block/cobbled_gabbro")
		.texture(Direction.SOUTH, "kubejs:block/cobbled_gabbro")
		.texture(Direction.EAST, "kubejs:block/cobbled_gabbro")
		.texture(Direction.WEST, "kubejs:block/cobbled_gabbro")
		.texture("particle", "kubejs:block/cobbled_gabbro")
		.suffocating(true)
		.viewBlocking(true)
		.redstoneConductor(true)
		.transparent(false);

	event
		.create("cobbled_breccia")
		.displayName("Cobbled Breccia")
		.mapColor("color_orange")
		.stoneSoundType()
		.tagBlock("minecraft:mineable/pickaxe")
		.tagBlock("minecraft:needs_wooden_tool")
		.hardness(2)
		.resistance(4)
		.opaque(true)
		.fullBlock(true)
		.requiresTool(true)
		.renderType("solid")
		.texture(Direction.UP, "kubejs:block/cobbled_breccia")
		.texture(Direction.DOWN, "kubejs:block/cobbled_breccia")
		.texture(Direction.NORTH, "kubejs:block/cobbled_breccia")
		.texture(Direction.SOUTH, "kubejs:block/cobbled_breccia")
		.texture(Direction.EAST, "kubejs:block/cobbled_breccia")
		.texture(Direction.WEST, "kubejs:block/cobbled_breccia")
		.texture("particle", "kubejs:block/cobbled_breccia")
		.suffocating(true)
		.viewBlocking(true)
		.redstoneConductor(true)
		.transparent(false);

	event
		.create("cobbled_galena")
		.displayName("Cobbled Galena")
		.mapColor("color_blue")
		.stoneSoundType()
		.tagBlock("minecraft:mineable/pickaxe")
		.tagBlock("minecraft:needs_wooden_tool")
		.hardness(2)
		.resistance(4)
		.opaque(true)
		.fullBlock(true)
		.requiresTool(true)
		.renderType("solid")
		.texture(Direction.UP, "kubejs:block/cobbled_galena")
		.texture(Direction.DOWN, "kubejs:block/cobbled_galena")
		.texture(Direction.NORTH, "kubejs:block/cobbled_galena")
		.texture(Direction.SOUTH, "kubejs:block/cobbled_galena")
		.texture(Direction.EAST, "kubejs:block/cobbled_galena")
		.texture(Direction.WEST, "kubejs:block/cobbled_galena")
		.texture("particle", "kubejs:block/cobbled_galena")
		.suffocating(true)
		.viewBlocking(true)
		.redstoneConductor(true)
		.transparent(false);
});

console.info("Blocks Created")
