#Hard disable entire modules. Use at your own risk and don't ask for support if you use this. Write modid = false to disable modules
#Sun Aug 31 15:42:01 EDT 2025
beautify=true
chipped=true
create=true
dramaticdoors=true
farmersdelight=true
friendsandfoes=true
handcrafted=true
mcwbridges=true
mcwdoors=true
mcwtrpdoors=true
refurbished_furniture=true
storagedrawers=true
twigs=true
